import { useState } from 'react'
import { useDispatch } from 'react-redux'
import { ChevronLeft, ChevronRight, Plus, Save } from 'lucide-react'
import { useWorkspace } from '../workspaces/useWorkspace'
import { actions } from '../../store/rootReducer'
import { execute } from '../../store/store'
import { Badge, Avatar, Button, Select, Input, Empty, Confirm } from '../../components/ui/WorkspaceUI'
import { day } from '../../data/seed'
import { formatDueDate } from '../../utils/date'
import { notify } from '../../utils/notify'

export default function TaskViews({ projectId, mine = false, compact = false, view = 'list' }) {
  const dispatch = useDispatch()
  const { data, tasks, projects, workspace, user, editable, pending } = useWorkspace()
  const [filters, setFilters] = useState({ query: '', assignee: '', status: '', priority: '', label: '', from: '', to: '', sort: 'dueDate', group: '', due: '' })
  const [selected, setSelected] = useState([])
  const [confirm, setConfirm] = useState(false)
  const [month, setMonth] = useState(() => new Date(new Date().getFullYear(), new Date().getMonth(), 1))
  const [presetName, setPresetName] = useState('')
  const project = projects.find(p => p.id === projectId)
  const statuses = project?.columns || [...new Set(projects.flatMap(p => p.columns))]
  const update = (key, value) => setFilters(f => ({ ...f, [key]: value }))
  let list = tasks.filter(t => (!t.parentId || mine) && (!projectId || t.projectId === projectId) && (!mine || t.assignee === user?.id) && !projects.find(p => p.id === t.projectId)?.archived)
  list = list.filter(t => `${t.title} ${t.description}`.toLowerCase().includes(filters.query.toLowerCase()) && (!filters.due || (filters.due === 'overdue' ? t.status !== 'Done' && t.dueDate && t.dueDate < day() : filters.due === 'today' ? t.dueDate === day() : t.dueDate > day())) && (!filters.assignee || t.assignee === filters.assignee) && (!filters.status || t.status === filters.status) && (!filters.priority || t.priority === filters.priority) && (!filters.label || t.labels.some(l => l.toLowerCase().includes(filters.label.toLowerCase()))) && (!filters.from || t.dueDate >= filters.from) && (!filters.to || (t.dueDate && t.dueDate <= filters.to)))
  list.sort((a, b) => filters.sort === 'priority' ? ['Urgent', 'High', 'Medium', 'Low'].indexOf(a.priority) - ['Urgent', 'High', 'Medium', 'Low'].indexOf(b.priority) : String(a[filters.sort] || 'zzzz').localeCompare(String(b[filters.sort] || 'zzzz')))
  const visible = compact ? list.slice(0, 6) : list
  const validSelected = selected.filter(id => list.some(t => t.id === id))
  const bulk = async (changes, remove = false) => { if (await dispatch(execute({ type: 'task.bulk', payload: { workspaceId: workspace?.id, ids: validSelected, changes, remove } }, remove ? 'Tasks deleted' : 'Tasks updated'))) { setSelected([]); setConfirm(false) } }
  const open = t => dispatch(actions.ui({ task: { id: t.id } }))
  const row = t => <tr key={t.id} className="border-t border-slate-100 text-[11px] dark:border-slate-800"><td className="w-8 px-3 py-3"><input aria-label={`Select ${t.title}`} type="checkbox" checked={validSelected.includes(t.id)} disabled={!editable || pending} onChange={e => setSelected(s => e.target.checked ? [...s, t.id] : s.filter(id => id !== t.id))} /></td><td className="py-3 pr-3"><button onClick={() => open(t)} className="text-left font-medium hover:text-violet-600">{t.title}</button>{t.parentId ? <span className="ml-2 text-[10px] text-violet-500">Subtask</span> : data.tasks.some(child => child.parentId === t.id) && <span className="ml-2 text-[10px] text-slate-400">{data.tasks.filter(child => child.parentId === t.id && child.status === 'Done').length}/{data.tasks.filter(child => child.parentId === t.id).length} subtasks</span>}<p className="mt-1 text-[9px] text-slate-400">{projects.find(p => p.id === t.projectId)?.name}</p></td><td className="p-2"><Badge color={t.priority === 'High' || t.priority === 'Urgent' ? 'red' : t.priority === 'Medium' ? 'blue' : 'gray'}>{t.priority}</Badge></td><td className="p-2"><Badge color={t.status === 'Done' ? 'green' : t.status === 'In progress' ? 'violet' : 'gray'}>{t.status}</Badge></td><td className="whitespace-nowrap p-2 text-slate-400">{formatDueDate(t.dueDate) || 'No date'}</td><td className="p-2"><Avatar small user={data.users.find(u => u.id === t.assignee)} /></td><td className="p-2"><input type="checkbox" aria-label={`Complete ${t.title}`} checked={t.status === 'Done'} disabled={!editable || pending} onChange={e => dispatch(execute({ type: 'task.save', payload: { ...t, workspaceId: workspace?.id, status: e.target.checked ? 'Done' : projects.find(p => p.id === t.projectId).columns[0] } }, 'Task status updated'))} /></td></tr>
  const table = items => <div className="overflow-x-auto"><table className="w-full min-w-[600px] text-left"><thead className="bg-slate-50 text-[9px] font-medium uppercase tracking-wide text-slate-400 dark:bg-slate-800"><tr><th className="p-3"><input aria-label="Select all visible tasks" type="checkbox" checked={items.length > 0 && items.every(t => selected.includes(t.id))} disabled={!editable || pending} onChange={e => setSelected(e.target.checked ? items.map(t => t.id) : [])} /></th><th><button onClick={() => update('sort', 'title')}>Task name</button></th><th><button onClick={() => update('sort', 'priority')}>Priority</button></th><th>Status</th><th><button onClick={() => update('sort', 'dueDate')}>Due date</button></th><th>Assignee</th><th>Done</th></tr></thead><tbody>{items.map(row)}</tbody></table></div>
  const groups = filters.group ? Object.groupBy(visible, t => filters.group === 'label' ? t.labels[0] || 'No label' : filters.group === 'assignee' ? data.users.find(u => u.id === t.assignee)?.name || 'Unassigned' : t[filters.group]) : null
  const start = new Date(month.getFullYear(), month.getMonth(), 1 - month.getDay())
  return <div>
    <div className="flex flex-wrap items-center gap-2 p-3"><Input className="max-w-44" placeholder="Filter tasks…" aria-label="Filter tasks" value={filters.query} onChange={e => update('query', e.target.value)} /><Select aria-label="Due date filter" value={filters.due || ''} onChange={e => update('due', e.target.value)}><option value="">Any due date</option><option value="overdue">Overdue</option><option value="today">Today</option><option value="upcoming">Upcoming</option></Select><Select aria-label="Status filter" value={filters.status} onChange={e => update('status', e.target.value)}><option value="">All statuses</option>{statuses.map(s => <option key={s}>{s}</option>)}</Select><Select aria-label="Priority filter" value={filters.priority} onChange={e => update('priority', e.target.value)}><option value="">All priorities</option>{['Low', 'Medium', 'High', 'Urgent'].map(s => <option key={s}>{s}</option>)}</Select>{!compact && <><Select aria-label="Assignee filter" value={filters.assignee} onChange={e => update('assignee', e.target.value)}><option value="">All assignees</option>{data.users.filter(u => workspace?.members.some(m => m.userId === u.id)).map(u => <option key={u.id} value={u.id}>{u.name}</option>)}</Select><Input className="max-w-28" placeholder="Label" aria-label="Label filter" value={filters.label} onChange={e => update('label', e.target.value)} /><Input className="max-w-36" type="date" aria-label="From date" value={filters.from} onChange={e => update('from', e.target.value)} /><Input className="max-w-36" type="date" aria-label="To date" value={filters.to} onChange={e => update('to', e.target.value)} /><Select aria-label="Sort tasks" value={filters.sort} onChange={e => update('sort', e.target.value)}>{['dueDate', 'priority', 'createdAt', 'title'].map(s => <option key={s} value={s}>Sort: {s}</option>)}</Select><Select aria-label="Group tasks" value={filters.group} onChange={e => update('group', e.target.value)}><option value="">No grouping</option>{['assignee', 'status', 'priority', 'label'].map(s => <option key={s}>{s}</option>)}</Select></>}
      <Button disabled={!editable || !projects.some(p => !p.archived)} onClick={() => dispatch(actions.ui({ task: { id: null, projectId } }))}><Plus size={12} />Add task</Button>
    </div>
    {!compact && <div className="flex flex-wrap gap-2 px-3 pb-3"><Select aria-label="Saved filters" value="" onChange={e => { const preset = data.presets.find(p => p.name === e.target.value && p.userId === user?.id); if (preset) setFilters(preset.filters) }}><option value="">Saved filters</option>{data.presets.filter(p => p.userId === user?.id).map(p => <option key={p.name}>{p.name}</option>)}</Select><Input className="max-w-40" aria-label="Filter preset name" placeholder="Name this filter" value={presetName} onChange={e => setPresetName(e.target.value)} /><Button onClick={() => { if (!presetName.trim()) { notify('Enter a filter name.', 'error'); return } dispatch(actions.preset({ name: presetName.trim(), filters })); setPresetName(''); notify('Filter saved.', 'success') }}><Save size={12} />Save filter</Button></div>}
    {editable && validSelected.length > 0 && <div className="flex flex-wrap items-center gap-2 bg-violet-50 p-3 text-xs text-violet-700"><span>{validSelected.length} selected</span><Select aria-label="Bulk status" value="" disabled={pending} onChange={e => bulk({ status: e.target.value })}><option value="">Change status</option>{statuses.map(s => <option key={s}>{s}</option>)}</Select><Select aria-label="Bulk assignee" value="" disabled={pending} onChange={e => bulk({ assignee: e.target.value === 'none' ? '' : e.target.value })}><option value="">Assign to…</option><option value="none">Unassigned</option>{data.users.filter(u => workspace.members.some(m => m.userId === u.id)).map(u => <option value={u.id} key={u.id}>{u.name}</option>)}</Select><Button disabled={pending} onClick={() => setConfirm(true)}>Delete selected</Button></div>}
    {!visible.length && <Empty title="No tasks match">Create a task or change your filters.</Empty>}
    {view === 'list' && (groups ? Object.entries(groups).map(([name, items]) => <div key={name}><h3 className="bg-slate-50 px-4 py-2 text-xs font-semibold dark:bg-slate-800">{name}</h3>{table(items)}</div>) : table(visible))}
    {view === 'board' && project && <div className="flex gap-3 overflow-x-auto p-3">{project.columns.map(status => <section key={status} className="min-h-64 min-w-56 flex-1 rounded-lg bg-slate-50 p-3 dark:bg-slate-800" onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); const t = tasks.find(t => t.id === e.dataTransfer.getData('text/plain')); if (t && editable && t.projectId === project.id) dispatch(execute({ type: 'task.save', payload: { ...t, status, workspaceId: workspace.id } }, 'Task moved')) }}><h3 className="mb-4 flex justify-between text-xs font-semibold">{status}<span className="text-slate-400">{visible.filter(t => t.status === status).length}</span></h3>{visible.filter(t => t.status === status).map(t => <article key={t.id} draggable={editable && !pending} onDragStart={e => e.dataTransfer.setData('text/plain', t.id)} className="mb-3 rounded-lg border border-slate-200 bg-white p-3 dark:border-slate-700 dark:bg-slate-900"><button onClick={() => open(t)} className="text-left text-xs font-medium">{t.title}</button><div className="mt-3 flex items-center justify-between"><Badge>{t.priority}</Badge><Avatar small user={data.users.find(u => u.id === t.assignee)} /></div><Select className="mt-3 w-full" aria-label={`Move ${t.title}`} value={t.status} disabled={!editable || pending} onChange={e => dispatch(execute({ type: 'task.save', payload: { ...t, status: e.target.value, workspaceId: workspace.id } }, 'Task moved'))}>{project.columns.map(c => <option key={c}>{c}</option>)}</Select></article>)}</section>)}</div>}
    {view === 'calendar' && <div className="p-3"><div className="mb-4 flex items-center justify-between"><Button aria-label="Previous month" onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() - 1, 1))}><ChevronLeft size={14} /></Button><h3 className="text-sm font-semibold">{month.toLocaleDateString(undefined, { month: 'long', year: 'numeric' })}</h3><Button aria-label="Next month" onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() + 1, 1))}><ChevronRight size={14} /></Button></div><div className="grid grid-cols-7 text-center text-[10px] text-slate-400">{['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'].map(d => <div key={d} className="p-2">{d}</div>)}</div><div className="grid grid-cols-7">{Array.from({ length: 42 }, (_, i) => { const date = new Date(start); date.setDate(date.getDate() + i); const key = `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`; return <div key={key} className={`min-h-24 border border-slate-100 p-1 dark:border-slate-800 ${date.getMonth() === month.getMonth() ? '' : 'opacity-40'}`}><span className="text-[10px]">{date.getDate()}</span>{visible.filter(t => t.dueDate === key).map(t => <button key={t.id} onClick={() => open(t)} className="mt-1 block w-full truncate rounded bg-violet-50 p-1 text-left text-[9px] text-violet-700">{t.title}</button>)}</div> })}</div><p className="mt-3 text-xs text-slate-400">{visible.filter(t => !t.dueDate).length} tasks without due dates are available in list view.</p></div>}
    {confirm && <Confirm title="Delete selected tasks?" busy={pending} onClose={() => setConfirm(false)} onConfirm={() => bulk({}, true)} />}
  </div>
}
