import { cloneElement, isValidElement, useEffect, useId, useRef } from 'react'
import { X } from 'lucide-react'

export function Button({ children, primary = false, className = '', ...props }) { return <button className={`inline-flex cursor-pointer items-center justify-center gap-2 rounded-md border px-3 py-2 text-xs font-medium transition-colors disabled:cursor-not-allowed disabled:opacity-40 ${primary ? 'border-[#7065dc] bg-[#7065dc] text-white hover:bg-[#6055cc]' : 'border-slate-200 bg-white text-slate-600 hover:bg-slate-50 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-200'} ${className}`} {...props}>{children}</button> }
export function Card({ children, className = '' }) { return <section className={`rounded-lg border border-[#e9ebf3] bg-white dark:border-slate-800 dark:bg-slate-900 ${className}`}>{children}</section> }
export function Avatar({ user, small = false }) { return user?.avatar ? <img src={user.avatar} alt={user.name} className={`${small ? 'size-6' : 'size-8'} rounded-full object-cover`} /> : <span title={user?.name || 'Unassigned'} className={`grid ${small ? 'size-6 text-[9px]' : 'size-8 text-[10px]'} shrink-0 place-items-center rounded-full bg-violet-100 font-semibold text-violet-600`}>{user?.name?.split(' ').map(p => p[0]).slice(0, 2).join('') || '?'}</span> }
export function Badge({ children, color = 'violet' }) { const colors = { violet: 'bg-violet-50 text-violet-600', red: 'bg-red-50 text-red-500', green: 'bg-emerald-50 text-emerald-600', blue: 'bg-blue-50 text-blue-500', amber: 'bg-amber-50 text-amber-600', gray: 'bg-slate-100 text-slate-500' }; return <span className={`inline-flex rounded px-1.5 py-0.5 text-[9px] font-medium ${colors[color] || colors.gray}`}>{children}</span> }
export function Field({ label, children }) { const generatedId = useId(); const control = isValidElement(children) && (children.type === Input || children.type === Select || ['input', 'select', 'textarea'].includes(children.type)); const id = children?.props?.id || generatedId; return <div className="block text-xs font-medium text-slate-600 dark:text-slate-300">{control ? <label htmlFor={id} className="mb-1.5 block">{label}</label> : <span className="mb-1.5 block">{label}</span>}{control ? cloneElement(children, { id }) : children}</div> }
export function Input(props) { return <input {...props} className={`w-full rounded-md border border-slate-200 bg-transparent px-3 py-2 text-xs outline-none focus:border-violet-400 dark:border-slate-700 ${props.className || ''}`} /> }
export function Select({ children, ...props }) { return <select {...props} className={`rounded-md border border-slate-200 bg-white px-2 py-2 text-xs text-slate-600 outline-none dark:border-slate-700 dark:bg-slate-900 dark:text-slate-200 ${props.className || ''}`}>{children}</select> }
export function Empty({ title = 'Nothing here yet', children }) { return <div className="p-10 text-center"><p className="text-sm font-medium">{title}</p><div className="mt-2 text-xs text-slate-400">{children}</div></div> }
export function Modal({ title, children, onClose, wide = false }) {
  const ref = useRef(null)
  useEffect(() => { const dialog = ref.current; dialog.showModal(); return () => dialog.close() }, [])
  return <dialog ref={ref} onCancel={onClose} onClick={e => { if (e.target === e.currentTarget) onClose() }} className={`fixed inset-0 m-auto max-h-[90svh] w-[calc(100%-2rem)] ${wide ? 'max-w-3xl' : 'max-w-lg'} overflow-auto rounded-xl border border-slate-200 bg-white p-0 text-slate-800 shadow-2xl backdrop:bg-slate-950/35 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-100`} aria-label={title}>
    <div className="sticky top-0 z-10 flex items-center justify-between border-b border-slate-100 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><h2 className="text-base font-semibold">{title}</h2><button onClick={onClose} aria-label="Close dialog" className="rounded p-1 hover:bg-slate-100"><X size={18} /></button></div><div className="p-5">{children}</div>
  </dialog>
}
export function Confirm({ title, onConfirm, onClose, busy }) { return <Modal title={title} onClose={onClose}><p className="text-sm text-slate-500">This removes the selected data and related records. Continue?</p><div className="mt-6 flex justify-end gap-2"><Button onClick={onClose}>Cancel</Button><Button primary disabled={busy} onClick={onConfirm}>Confirm removal</Button></div></Modal> }
